/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin application project to get you started.
 * For more details take a look at the 'Building Java & JVM projects' chapter in the Gradle
 * User Manual available at https://docs.gradle.org/7.3/userguide/building_java_projects.html
 */

plugins {
    id("com.android.application") version "7.1.0-beta02"
    id("org.jetbrains.kotlin.android") version "1.5.30"
}

android {
    compileSdk = 28

    defaultConfig {
        applicationId = "cr.ac.tec.ce3101.tabas"
        minSdk = 15
        targetSdk = 28
        buildToolsVersion = "31.0.0"
        versionCode = 1
        versionName = "1.0"
    }

    buildTypes {
        getByName("release") {
            isMinifyEnabled = true
        }
    }
}

dependencies {
    implementation("androidx.appcompat:appcompat:1.3.0")
    implementation("androidx.appcompat:appcompat-resources:1.3.0")
}
