/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin application project to get you started.
 * For more details take a look at the 'Building Java & JVM projects' chapter in the Gradle
 * User Manual available at https://docs.gradle.org/7.3/userguide/building_java_projects.html
 */

plugins {
    id("com.android.application") version "7.1.0-beta02"
    id("org.jetbrains.kotlin.android") version "1.5.30"
    id("com.ncorti.ktfmt.gradle") version "0.8.0"
}

android {
    compileSdk = 29

    defaultConfig {
        applicationId = "cr.ac.tec.ce3101.tabas"
        minSdk = 15
        targetSdk = 29
        buildToolsVersion = "31.0.0"
        versionCode = 1
        versionName = "1.0"
    }

    buildTypes {
        getByName("release") {
            isMinifyEnabled = true
        }
    }

    lint {
	    abortOnError = false
	}
}

dependencies {
    implementation("androidx.appcompat:appcompat:1.3.0")
    implementation("androidx.appcompat:appcompat-resources:1.3.0")
    implementation("androidx.viewpager:viewpager:1.0.0")
    implementation("androidx.fragment:fragment:1.3.0")
    implementation("com.google.android.material:material:1.4.0")
    implementation("com.squareup.retrofit2:retrofit:2.1.0")
    implementation("com.squareup.retrofit2:converter-gson:2.1.0")
}
